package eg.edu.alexu.csd.oop.draw;

import java.awt.*;
import java.io.*;
import java.net.*;
import com.sun.*;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

import eg.edu.alexu.csd.oop.draw.Draw;

public class g extends JFrame {

	Panel panel; 

	public static Color BackColor, ForeColor;
	public static Color FillColor;

	public g() {
		setResizable(false);
		setMinimumSize(new Dimension(850, 800));
		initComponents();
		panel = new Panel();
		panel.setBounds(0, 50, 1851, 740);
		panel.setAlignmentX(Component.LEFT_ALIGNMENT);
		Rectangle f = this.getBounds();
		getContentPane().add(panel, BorderLayout.CENTER);
		GroupLayout gl_panel = new GroupLayout(panel);
		gl_panel.setHorizontalGroup(
				gl_panel.createParallelGroup(Alignment.LEADING)
				.addGap(0, 1851, Short.MAX_VALUE)
				);
		gl_panel.setVerticalGroup(
				gl_panel.createParallelGroup(Alignment.LEADING)
				.addGap(0, 740, Short.MAX_VALUE)
				);
		panel.setLayout(gl_panel);
		getContentPane().add(panel);
		BackColor = new Color(255,255,255);
		ForeColor = panel.getForeground();
		panel.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		
		jMenuBar1 = new javax.swing.JMenuBar();
		
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		
		jToolBar1 = new javax.swing.JToolBar();
		toolBar = new javax.swing.JToolBar();
		toolBar2 = new JToolBar();
		
		jButton4 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		

		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Paint");
		
		jMenuItem2.setText("jMenuItem2");
		
		toolBar.setBounds(280, 0, 313, 50);
		jToolBar1.setRollover(true);
		jToolBar1.setBounds(0, 0, 300, 50);
		jToolBar1.setBackground(UIManager.getColor("scrollbar"));

		
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/line.png")));
		jButton4.setToolTipText("Draw a line");
		jButton4.setBorderPainted(false);
		jButton4.setMaximumSize(new Dimension(40, 9));
		jButton4.setForeground(Color.BLACK);
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton4);


		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/ellipse.png")));
		jButton1.setToolTipText("Draw an Ellipse");
		jButton1.setBorderPainted(false);
		jButton1.setMaximumSize(new Dimension(40, 9));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton1);


		jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/circle.png")));
		jButton15.setToolTipText("Draw a Circle");
		jButton15.setBorderPainted(false);
		jButton15.setMaximumSize(new Dimension(40, 9));
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton15);


		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/square.png")));
		jButton2.setToolTipText("Draw a square");
		jButton2.setBorderPainted(false);
		jButton2.setMaximumSize(new Dimension(40, 9));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton2);


		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/rectangle.png")));
		jButton3.setToolTipText("Draw a rectangle");
		jButton3.setBorderPainted(false);
		jButton3.setMaximumSize(new Dimension(40, 9));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton3);


		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/triangle.png")));
		jButton5.setToolTipText("Draw a triangle");
		jButton5.setBorderPainted(false);
		jButton5.setMaximumSize(new Dimension(40, 9));
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton5);

		jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/paint.png")));
		jButton10.setText("Back-Color");
		jButton10.setToolTipText("Pick a color to fill the shape with.");
		jButton10.setBorderPainted(false);
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});
		toolBar.add(jButton10);
		
		jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/brush.png")));
		jButton9.setText("Border-Color");
		jButton9.setToolTipText("Pick a color for the border of the shape.");
		jButton9.setBorderPainted(false);
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		toolBar.add(jButton9);

		jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/paint-bucket.png")));
		jButton13.setText("Fill-Color");
		jButton13.setBorderPainted(false);
		jButton13.setToolTipText("click on a shape on the canvas to fill it with the foreground color you pick.");
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});
		toolBar.add(jButton13);		
		

		toolBar2.setBounds(600, 0, 300, 50);

		jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/trash-can.png")));
		jButton14.setToolTipText("Delete");
		jButton14.setBorderPainted(false);
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});
		toolBar2.add(jButton14);

		jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/resize.png")));
		jButton12.setToolTipText("Resize");
		jButton12.setBorderPainted(false);
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});
		toolBar2.add(jButton12);
        
		jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/move.png")));
		jButton11.setToolTipText("Move");
		jButton11.setBorderPainted(false);
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});
		toolBar2.add(jButton11);
		
		jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/undo.png")));
		jButton7.setToolTipText("Undo");
		jButton7.setBorderPainted(false);
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		toolBar2.add(jButton7);
		
		jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eg/edu/alexu/csd/oop/img/redo.png")));
		jButton6.setToolTipText("Redo");
		jButton6.setBorderPainted(false);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		toolBar2.add(jButton6);
		
		
		jMenu3.setText("File");

		jMenuItem5.setText("Open");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem5);


		jMenuItem6.setText("Save");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem6);


		jMenuItem1.setText("Exit");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem1);
		jMenuBar1.add(jMenu3);

		
		jMenu2.setText("Plugins");
		
        jMenuItem3.setText("Load");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);
		setJMenuBar(jMenuBar1);
		
		getContentPane().setLayout(null);
		
		getContentPane().add(jToolBar1);
		getContentPane().add(toolBar);
		getContentPane().add(toolBar2);

	}// </editor-fold>//GEN-END:initComponents

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		panel.myEngine.undo();
	}//GEN-LAST:event_jButton7ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		panel.myEngine.redo();
	}//GEN-LAST:event_jButton6ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Line);
	}//GEN-LAST:event_jButton4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Ellipse);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Square);
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Rectangle);
	}//GEN-LAST:event_jButton3ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Triangle);
	}//GEN-LAST:event_jButton5ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
		ForeColor = JColorChooser.showDialog(null, "Please Choose your Border Color", ForeColor);
	}//GEN-LAST:event_jButton9ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
		BackColor = JColorChooser.showDialog(null, "Please Choose your Back Color", BackColor);
	}//GEN-LAST:event_jButton10ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
		panel.resetAll();
		panel.moving = true;
	}//GEN-LAST:event_jButton11ActionPerformed

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
		panel.resetAll();
		panel.resize = true;
	}//GEN-LAST:event_jButton12ActionPerformed

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
		panel.resetAll();
		panel.recoloring = true;
		FillColor = JColorChooser.showDialog(null, "Please Choose your Fill Color", FillColor);
	}//GEN-LAST:event_jButton13ActionPerformed

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
		panel.resetAll();
		panel.deleting = true;
	}//GEN-LAST:event_jButton14ActionPerformed

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
		panel.setCurrentShapeType(ShapeTypes.Circle);
	}//GEN-LAST:event_jButton15ActionPerformed
	

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("XML File", "xml"));
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("JSON File", "json"));
		fileChooser.setDialogTitle("Save as XML OR JSON File");
		if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
			File file = fileChooser.getSelectedFile();
			if (file != null) {
				panel.myEngine.save(file.getAbsolutePath());
			}
		}
	}//GEN-LAST:event_jMenuItem6ActionPerformed

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("XML File", "xml"));
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("JSON File", "json"));
		fileChooser.setDialogTitle("Load XML OR JSON File");

		if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			File file = fileChooser.getSelectedFile();
			if (file != null) {
				panel.myEngine.load(file.getAbsolutePath());
			}
			panel.repaint();

		}
	}//GEN-LAST:event_jMenuItem5ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		System.exit(0);
	}//GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("JAR File", "jar"));
        fileChooser.setDialogTitle("Load JAR file");

        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (file != null) {
                panel.myEngine.installPluginShape(file.getPath());
            }
        }
        
    } 

	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(g.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(g.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(g.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(g.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new g().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JToolBar toolBar;
	private javax.swing.JToolBar toolBar2;
}
